XTT-948 Catch NoSuchMethodError in cling
An 'eth0' device in Android (which presumably means Honeycomb GTV)
is saying it doesn't have an 'isUp()' method. Not sure why this is
happening as the source indicates it should have this method. Just
catching the error, logging and moving on.